import './globals.css'
import { Inter } from 'next/font/google'
import Header from "../components/Header"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='h-screen'>
      <body className={inter.className}>
        <Header/>
        <main className='h-[calc(100vh-112px)] flex justify-center items-end'>
          {children}
        </main>
      </body>
    </html>
  )
}
